### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by baguadev** [ReikaKalseki/GameCalendar#1]
Hello.
Checked your repository, was able to build it using maven. Now trying to run your app but it fails because cannot find data to build calendar.
Could you please provide some sample data to be able to run the app ?
Thanks

**Comment by ReikaKalseki** [comment]
I never expected there to be actual interest in this. :P

This repo used to contain my dataset, but apparently that got removed at some point.

I have added a folder "SampleData"; this can be renamed to "Data" as expected and used.

However, the intent of the program was always for rendering whatever data mattered to you; without data to supply there is not really a point.
